# Generated by Django 5.2.7 on 2025-11-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_investment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='bill',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='source',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='saving',
            old_name='category',
            new_name='name',
        ),
    ]
